Objetivo 0
amerigal/proyecto_iv pull request #1
Opened 2021-09-23 05:50 UTC by amerigal

2021-09-23 08:23 UTC, amerigal commented
Pensándolo más detenidamente y tras la sesión de clase no me termina de convencer la idea que había presentado. Voy a darle más vueltas estos días y la actualizo.

2021-09-27 17:53 UTC, amerigal commented
Ya está actualizada la idea. Listo para revisión.

2021-09-29 06:57 UTC, JJ requested changes
Me temo que te quedarían varios pasos para alcanzar el objetivo, como se ha especificado en el comentario.

2021-09-29 06:57 UTC, JJ commented on README.md
> +
OK, tengo clara cuál es la lógica de negocio aquí. Lo que no tengo tan claro es que tú entiendas que la lógica de negocio la tienes que programar tú, no me vale biblioteca externa. ¿Lo entiendes así? ¿Cuál sería, según tú, la lógica de negocio?
Aparte, ¿qué beneficio se obtendría con que esto estuviera en la nube y no un simple app?

2021-09-29 07:59 UTC, amerigal commented on README.md
> +
Efectivamente no estaba seguro de hasta qué punto era una restricción el uso de una biblioteca externa. Una parte importante de la lógica de negocio sería el reconocimiento de los caracteres en la foto del recibo y probablemente no sea algo sencillo de implementar ni adecuado para la asignatura. Entiendo entonces que tendré que pensar otra idea.

En cualquier caso, y por aclararme con respecto a lo de subir a la nube el sistema desarrollado, había pensado en que la información de todos los usuarios con respecto a cuáles son los productos más comprados podría ser vendida a quién le interesara, en cuyo caso sería beneficioso gestionarla de manera centralizada. No sé si esa sería justificación suficiente para que estuviera en la nube.

2021-09-29 08:07 UTC, JJ commented on README.md
> +
O darle una vuelta a esta idea, por ejemplo suponiendo que ya has extraído los caracteres, pero que diferentes tickets van a tener diferente formato. Tendrás que teclear a mano ese formato (o usar un OCR y corregirlo), pero ya extraer información de ahí no es fácil. Por supuesto, lo que mencionas podría ser la verdadera lógica de negocio y lo justificaría.

2021-09-29 10:42 UTC, amerigal commented on README.md
> +
He estado probando con distintas herramientas de OCR accesibles online y no funcionan del todo bien, además de que los formatos de los tickets son demasiado variados y no parece fácil hacer una implementación lo suficientemente genérica para extraer la información de los mismos. Creo que sería más conveniente abordar otro problema.

La verdad es que estoy un poco atascado en ese sentido y me pregunto si me podría dar alguna orientación sobre áreas o temas en los que centrar la idea. Me resulta complicado encontrar el punto entre que sea lo suficientemente compleja para que no se reduzca a un almacen y búsqueda, que tenga una lógica de negocio que le de valor y permita comercializarla, pero que tampoco sea demasiado complicada como para poder desarrollarla en un tiempo razonable sin utilizar funcionalidades de bibliotecas externas. Seguiré pensando en cualquier caso.

2021-09-29 13:57 UTC, JJ commented on README.md
> +
> He estado probando con distintas herramientas de OCR accesibles online y no funcionan del todo bien, además de que los formatos de los tickets son demasiado variados y no parece fácil hacer una implementación lo suficientemente genérica para extraer la información de los mismos. Creo que sería más conveniente abordar otro problema.
> 

OK. Incluso aunque funcionaran bien, no serían tu código.

> La verdad es que estoy un poco atascado en ese sentido y me pregunto si me podría dar alguna orientación sobre áreas o temas en los que centrar la idea. Me resulta complicado encontrar el punto entre que sea lo suficientemente compleja para que no se reduzca a un almacen y búsqueda, que tenga una lógica de negocio que le de valor y permita comercializarla, pero que tampoco sea demasiado complicada como para poder desarrollarla en un tiempo razonable sin utilizar funcionalidades de bibliotecas externas. Seguiré pensando en cualquier caso.

Como dijimos en clase, lo que hay que hacer es entender el problema y empatizar con las personas a las que tienes que resolver el problema. Yo no puedo darte eso, porque entonces es mi responsabilidad indicarte todos los posibles aspectos del mismo. Además, lo que busco es que seais capaces de definir un problema, ese es el objetivo 0. 

Como sugerencia, puedes usar los objetivos del milenio para buscar algún problema que merezca la pena, alguno con el que simpatices. O algún tipo de noticia que encuentres en el diario, o algo que hagas tú o alguien cercano de forma cotidiana y tenga que hacer mejor. Pero eso ya os lo dije en clase.

2021-09-30 17:33 UTC, amerigal commented
Listo para revisión.

2021-10-02 06:51 UTC, JJ approved these changes
:+1:

2021-10-03 17:27 UTC, merged